const $=id=>document.getElementById(id);
const PARAM_TIME_BASE_NS=50;
const PARAM_MAX_BOARD_VALUE=65535;
const PARAM_MAX_NS=PARAM_MAX_BOARD_VALUE*PARAM_TIME_BASE_NS;
let allFiles=[],binFiles=[],selected=null,currentPage='params',currentParamType='control';
let boardParamStates={},paramCounts={},paramBusy=false,toastTimer=0,boardConnectCanceled=false,downloadConfirmResolver=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function showToast(s,duration=1200){const t=$('toast');if(toastTimer)clearTimeout(toastTimer);t.textContent=s;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),duration);}
async function readErr(r){try{const j=await r.clone().json();return j.error||r.statusText}catch(e){return await r.text()||r.statusText}}
function isBin(f){return !f.is_dir&&(f.is_param_bin||/\.bin$/i.test(f.name||''));}
function boardLabel(f){return f.boardName||f.displayName||'未识别板卡配置';}
function normParamType(p){return String(p.paramType||'').toLowerCase();}
function currentBoardKey(){return selected&&selected.path?selected.path:null;}
function getCurrentBoardState(){const key=currentBoardKey();if(!key)return null;if(!boardParamStates[key])boardParamStates[key]={parameters:[],currentParamType:'control',parsed:false};return boardParamStates[key];}
function getCurrentParams(){const s=getCurrentBoardState();return s?s.parameters:[];}
function updateParamButtons(){const ready=!!selected&&getCurrentParams().length>0;$('btnDefault').disabled=paramBusy||!ready;$('btnReadback').disabled=paramBusy||!ready;$('btnDownload').disabled=paramBusy||!ready;}
function setParamBusy(b){paramBusy=b;updateParamButtons();}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function openBoardConnectDialog(actionText){$('connectAction').textContent=actionText||'正在和参数板卡握手';$('connectMessage').textContent='请保持设备连接稳定。';$('connectDialog').classList.remove('hidden');}
function closeBoardConnectDialog(){$('connectDialog').classList.add('hidden');}
async function cancelBoardConnect(){boardConnectCanceled=true;$('connectMessage').textContent='正在取消连接...';try{await fetch('/api/param/connect/cancel',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'',keepalive:true});}catch(e){}}
async function postForm(url,fields){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});let j=null;try{j=await r.json();}catch(e){j={ok:false,error:r.statusText};}if(r.status===401){location.href='/';return null;}if(!r.ok||!j.ok)throw new Error((j&&j.error)||r.statusText);return j;}
async function getParamBoardStatus(opId,path){let url='/api/param/status?id='+encodeURIComponent(opId);if(path)url+='&path='+encodeURIComponent(path);const r=await fetch(url,{cache:'no-store'});let j=null;try{j=await r.json();}catch(e){j={ok:false,error:r.statusText};}if(r.status===401){location.href='/';return null;}if(!r.ok||!j.ok)throw new Error((j&&j.error)||r.statusText);return j;}
async function runParamBoardOperation(actionText,url,fields){boardConnectCanceled=false;openBoardConnectDialog(actionText);try{const started=await postForm(url,fields);if(!started||!started.opId)return started;const opId=started.opId;while(!boardConnectCanceled){const status=await getParamBoardStatus(opId,fields&&fields.path);if(!status)return null;$('connectMessage').textContent=status.message||'正在执行参数操作';if(status.state==='done')return status;if(status.state==='canceled')return null;if(status.state==='failed')throw new Error(status.error||status.message||'参数板卡操作失败');if(status.state!=='running')throw new Error(status.error||status.message||'参数板卡状态异常');await sleep(350);}await fetch('/api/param/connect/cancel',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'',keepalive:true});return null;}catch(e){if(boardConnectCanceled)return null;throw e;}finally{closeBoardConnectDialog();boardConnectCanceled=false;}}
function switchPage(page){currentPage=page==='about'?'about':'params';$('paramPage').classList.toggle('hidden',currentPage!=='params');$('aboutPage').classList.toggle('hidden',currentPage!=='about');$('navParams').classList.toggle('active',currentPage==='params');$('navAbout').classList.toggle('active',currentPage==='about');document.querySelector('.root').classList.toggle('page-about',currentPage==='about');if(currentPage==='about')switchAboutSection('intro');}
function renderBins(){binFiles=allFiles.filter(isBin).sort((a,b)=>boardLabel(a).localeCompare(boardLabel(b),'zh-CN'));$('binCount').textContent=binFiles.length;$('binEmpty').classList.toggle('hidden',binFiles.length>0);$('binList').innerHTML=binFiles.map(f=>{const active=!!(selected&&selected.path===f.path);const count=paramCounts[f.path];return '<button class="bin'+(active?' active':'')+'" data-path="'+esc(f.path)+'" title="'+esc(boardLabel(f))+'"><span class="bin-name">'+esc(boardLabel(f))+'</span><span class="bin-count">'+esc(count!=null?'共 '+count+' 项参数':'尚未解析')+'</span><span class="bin-hint">点击查看参数</span></button>';}).join('');document.querySelectorAll('.bin').forEach(b=>b.onclick=()=>selectBin(b.dataset.path,true));}
async function loadFiles(){try{$('hint').textContent='正在加载板卡列表...';const r=await fetch('/files',{cache:'no-store'});const j=await r.json();if(r.status===401){location.href='/';return;}if(!r.ok)throw new Error(j.error||r.statusText);allFiles=(j.files||[]).filter(f=>f.name!=='System Volume Information');binFiles=allFiles.filter(isBin).sort((a,b)=>boardLabel(a).localeCompare(boardLabel(b),'zh-CN'));if(selected){const still=binFiles.find(f=>f.path===selected.path);selected=still||null;}renderBins();if(!selected&&binFiles.length>0)selectBin(binFiles[0].path,true);else if(!selected){$('title').textContent='请选择一个板卡';$('hint').textContent='暂无可配置板卡。';$('result').classList.add('hidden');updateParamButtons();}}catch(e){$('hint').textContent='加载失败：'+e.message;showToast('加载失败：'+e.message,1800);}}
function selectBin(path,parseNow=true){selected=binFiles.find(f=>f.path===path)||null;renderBins();if(!selected)return;$('title').textContent=boardLabel(selected);$('hint').textContent='正在解析板卡配置...';if(!paramBusy)setParamBusy(false);const state=getCurrentBoardState();if(state&&state.parsed){currentParamType=state.currentParamType||'control';renderParamTable();$('result').classList.remove('hidden');$('parseErr').classList.add('hidden');$('hint').textContent='';return;}if(parseNow)parseSelected();}
function switchParamType(type){const state=getCurrentBoardState();if(state)state.currentParamType=type;currentParamType=type;renderParamTable();}
function renderParamTable(){const state=getCurrentBoardState();const params=getCurrentParams();const active=(state&&state.currentParamType)||currentParamType||'control';currentParamType=active;const control=params.filter(p=>normParamType(p)==='control');const protection=params.filter(p=>normParamType(p)==='protection');$('controlCount').textContent=control.length;$('protectionCount').textContent=protection.length;$('tabControl').classList.toggle('active',active==='control');$('tabProtection').classList.toggle('active',active==='protection');const list=params.map((p,i)=>({p,i})).filter(x=>normParamType(x.p)===active);const rows=[];for(let row=0;row<Math.ceil(list.length/2);row++){const left=list[row];const right=list[row+Math.ceil(list.length/2)];const cells=[left,right].map(x=>{if(!x)return '<td class="name param-empty-cell"></td><td class="value param-empty-cell"></td>';const v=x.p.currentValue==null?'':x.p.currentValue;return '<td class="name">'+esc(x.p.name)+'</td><td class="value"><span class="param-value-cell"><input class="param-value-input" type="number" min="0" max="'+PARAM_MAX_NS+'" step="'+PARAM_TIME_BASE_NS+'" inputmode="numeric" data-index="'+x.i+'" value="'+esc(v)+'"></span></td>';}).join('');rows.push('<tr>'+cells+'</tr>');}$('paramRows').innerHTML=rows.join('');document.querySelectorAll('.param-value-input').forEach(input=>{input.oninput=()=>{const idx=Number(input.dataset.index);if(!params[idx])return;if(input.value===''){delete params[idx].currentValue;return;}let v=Number(input.value);if(!Number.isFinite(v)){delete params[idx].currentValue;input.value='';return;}if(v<0)v=0;if(v>PARAM_MAX_NS)v=PARAM_MAX_NS;v=Math.floor(v);params[idx].currentValue=v;input.value=String(v);};});$('paramEmpty').classList.toggle('hidden',list.length>0);$('paramTable').classList.toggle('hidden',list.length===0);updateParamButtons();}
async function parseSelected(){if(!selected)return;const path=selected.path;$('parseErr').classList.add('hidden');$('result').classList.add('hidden');$('title').textContent=boardLabel(selected);$('hint').textContent='系统正在解析板卡配置...';if(!paramBusy)setParamBusy(false);try{const r=await fetch('/api/bin/parse?path='+encodeURIComponent(path),{cache:'no-store'});const j=await r.json();if(r.status===401){location.href='/';return;}if(!r.ok||!j.ok)throw new Error(j.error||r.statusText);const file=binFiles.find(f=>f.path===path)||allFiles.find(f=>f.path===path);if(j.boardName&&file){file.boardName=j.boardName;file.displayName=j.boardName;}const state=boardParamStates[path]||{parameters:[],currentParamType:'control',parsed:false};const oldParams=state.parameters||[];const newParams=(j.parameters||[]).map((p,i)=>{const oldByAddr=oldParams.find(o=>o&&o.address!=null&&p.address!=null&&Number(o.address)===Number(p.address));const oldByKey=oldParams.find(o=>o&&o.name===p.name&&normParamType(o)===normParamType(p));const old=oldByAddr||oldByKey||oldParams[i];return old&&old.currentValue!=null?{...p,currentValue:old.currentValue}:{...p,currentValue:p.defaultValue};});state.parameters=newParams;state.currentParamType='control';state.parsed=true;boardParamStates[path]=state;paramCounts[path]=(typeof j.visibleCount==='number')?j.visibleCount:newParams.length;if(selected&&selected.path===path&&j.boardName){selected.boardName=j.boardName;selected.displayName=j.boardName;$('title').textContent=j.boardName;}renderBins();if(selected&&selected.path===path){currentParamType=state.currentParamType;renderParamTable();$('result').classList.remove('hidden');$('parseErr').classList.add('hidden');$('hint').textContent='';}}catch(e){if(selected&&selected.path===path){$('parseErr').textContent='解析失败：'+e.message;$('parseErr').classList.remove('hidden');$('hint').textContent='解析失败，请确认该文件由配套工具生成且未损坏';}updateParamButtons();}}
function actDefault(){const state=getCurrentBoardState();if(!selected||!state||state.parameters.length===0)return;state.parameters.forEach(p=>{p.currentValue=p.defaultValue;});renderParamTable();showToast('默认参数填充成功');}
async function actReadback(){const state=getCurrentBoardState();if(!selected||!state)return;const path=selected.path;try{setParamBusy(true);showToast('正在回读参数...',1200);const j=await runParamBoardOperation('正在连接板卡并回读参数','/api/param/readback',{path});if(!j)return;if(!(selected&&selected.path===path))return;const valueMap={};(j.values||[]).forEach(item=>{valueMap[Number(item.address)]=item.value;});state.parameters.forEach(p=>{const addr=Number(p.address);if(Object.prototype.hasOwnProperty.call(valueMap,addr))p.currentValue=valueMap[addr];});renderParamTable();showToast('参数回读成功');}catch(e){showToast('参数回读失败：'+e.message,1800);}finally{setParamBusy(false);}}
function formatParamValue(v){if(v==null||v==='')return '未回读';const n=Number(v);return Number.isFinite(n)?Math.floor(n)+' ns':String(v);}
function collectDownloadPayload(params){const pairs=[],items=[];for(const p of params){const addr=Number(p.address);if(!Number.isInteger(addr)||addr<0||addr>71){showToast('参数地址无效',1800);return null;}if(p.currentValue==null||p.currentValue===''){showToast('请先填写所有可见参数',1800);return null;}let v=Number(p.currentValue);if(!Number.isFinite(v)||v<0||v>PARAM_MAX_NS){showToast('参数值必须在 0~'+PARAM_MAX_NS+' ns',1800);return null;}v=Math.floor(v);if(v%PARAM_TIME_BASE_NS!==0){showToast('参数值必须是 '+PARAM_TIME_BASE_NS+'ns 的整数倍',1800);return null;}pairs.push(addr+':'+v);items.push({address:addr,name:p.name||'未命名参数',value:v});}return {pairs,items};}
function buildDownloadDiffs(readbackValues,downloadItems){const valueMap={};(readbackValues||[]).forEach(item=>{const addr=Number(item.address);if(Number.isInteger(addr))valueMap[addr]=item.value;});return downloadItems.reduce((list,item)=>{const has=Object.prototype.hasOwnProperty.call(valueMap,item.address);const readbackValue=has?valueMap[item.address]:null;const readbackNumber=Number(readbackValue);if(!has||!Number.isFinite(readbackNumber)||Math.floor(readbackNumber)!==item.value)list.push({name:item.name,readbackValue,inputValue:item.value});return list;},[]);}
function renderDownloadDiffDialog(diffs){const hasDiff=diffs.length>0;$('downloadDiffCount').textContent=hasDiff?'共 '+diffs.length+' 项差异':'0 项差异';$('downloadDiffWrap').classList.toggle('hidden',!hasDiff);$('downloadDiffEmpty').classList.toggle('hidden',hasDiff);$('downloadDiffRows').innerHTML=diffs.map(d=>'<div class="download-diff-row"><div class="download-diff-cell readback"><div class="download-diff-name">'+esc(d.name)+'</div><div class="download-diff-value">'+esc(formatParamValue(d.readbackValue))+'</div></div><div class="download-diff-cell input"><div class="download-diff-name">'+esc(d.name)+'</div><div class="download-diff-value">'+esc(formatParamValue(d.inputValue))+'</div></div></div>').join('');}
function openDownloadConfirmDialog(diffs){renderDownloadDiffDialog(diffs);$('downloadConfirmDialog').classList.remove('hidden');return new Promise(resolve=>{downloadConfirmResolver=resolve;});}
function closeDownloadConfirmDialog(){$('downloadConfirmDialog').classList.add('hidden');}
function resolveDownloadConfirm(confirmed){const resolve=downloadConfirmResolver;downloadConfirmResolver=null;closeDownloadConfirmDialog();if(resolve)resolve(confirmed);}
function cancelDownloadConfirm(){resolveDownloadConfirm(false);}
function confirmDownloadConfirm(){resolveDownloadConfirm(true);}
async function actDownload(){const state=getCurrentBoardState();if(!selected||!state)return;const path=selected.path;const payload=collectDownloadPayload(state.parameters);if(!payload)return;try{setParamBusy(true);showToast('正在回读参数...',1200);const readback=await runParamBoardOperation('正在连接板卡并回读参数','/api/param/readback',{path});if(!readback)return;if(!(selected&&selected.path===path))return;const diffs=buildDownloadDiffs(readback.values,payload.items);const confirmed=await openDownloadConfirmDialog(diffs);if(!confirmed){showToast('已取消下载');return;}showToast('正在下载参数...',1200);const j=await runParamBoardOperation('正在连接板卡并下载参数','/api/param/download',{path,values:payload.pairs.join(',')});if(!j)return;showToast('参数下载成功');}catch(e){showToast('参数下载失败：'+e.message,1800);}finally{setParamBusy(false);}}
function switchAboutSection(id){document.querySelectorAll('[data-about-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.aboutTab===id));document.querySelectorAll('[data-about-section]').forEach(sec=>{sec.hidden=sec.dataset.aboutSection!==id;});}
async function renderBuildTime(){const el=$('appBuildTime');if(!el)return;try{const r=await fetch('/api/app/info',{cache:'no-store'});const j=await r.json();if(r.status===401){location.href='/';return;}if(!r.ok||!j.ok)throw new Error(j.error||r.statusText);el.textContent=j.buildTime||'未获取';}catch(e){el.textContent='未获取';}}
async function checkAuth(){try{const r=await fetch('/api/auth/status',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok){location.href='/';return false;}return true;}catch(e){location.href='/';return false;}}
async function logout(){try{await fetch('/api/logout',{method:'POST',cache:'no-store'});}catch(e){}location.href='/';}
async function initApp(){if(await checkAuth()){await loadFiles();await renderBuildTime();}}
initApp();
